#!/bin/bash

# Build docker image
git clone https://github.com/raulbrito/docker-graphite /tmp/docker-graphite
docker build -q=true -t raulbrito/graphite /tmp/docker-graphite
rm -rf /tmp/docker-graphite
